// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// 프로젝트 루트의 .env를 명시적으로 로드 (migrate dev 등 CLI에서 url 인식되도록)
config({ path: path.resolve(process.cwd(), ".env") });

const databaseUrl = process.env["DATABASE_URL"];
if (!databaseUrl) {
  throw new Error(
    "DATABASE_URL이 비어 있습니다. 프로젝트 루트의 .env 파일을 열어 다음 한 줄을 추가한 뒤 다시 실행하세요 (등호 앞뒤 공백 없이):\n  DATABASE_URL=\"postgresql://USER:PASSWORD@localhost:5432/DB이름\""
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
