// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// 프로젝트 루트의 .env를 명시적으로 로드 (migrate dev 등 CLI에서 url 인식되도록)
config({ path: path.resolve(process.cwd(), ".env") });

// 마이그레이션/CLI는 direct connection 사용 (풀러 우회). 없으면 DATABASE_URL 사용.
const directUrl = process.env["DIRECT_URL"] || process.env["DATABASE_URL"];
if (!directUrl) {
  throw new Error(
    "DIRECT_URL 또는 DATABASE_URL이 필요합니다. .env에 DATABASE_URL=\"postgresql://...\" 또는 DIRECT_URL=\"postgresql://...\" 를 추가하세요."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: directUrl,
  },
});
